all:
	@make --no-print-directory -C SDL
	@make --no-print-directory -C SFML
	@make --no-print-directory -C Libcaca

clean:
	@make clean  --no-print-directory -C SDL
	@make clean  --no-print-directory -C SFML
	@make clean  --no-print-directory -C Libcaca

fclean:
	@make fclean  --no-print-directory -C SDL
	@make fclean  --no-print-directory -C SFML
	@make fclean  --no-print-directory -C Libcaca

re:
	@make re  --no-print-directory -C SDL
	@make re  --no-print-directory -C SFML
	@make re  --no-print-directory -C Libcaca