all:
	@make --no-print-directory -C Snake
	@make --no-print-directory -C SolarFox
	
clean:
	@make clean  --no-print-directory -C Snake
	@make clean --no-print-directory -C SolarFox

fclean:
	@make fclean  --no-print-directory -C Snake
	@make fclean --no-print-directory -C SolarFox
	

re:
	@make re  --no-print-directory -C Snake
	@make re --no-print-directory -C SolarFox